package main

import (
	"os"
	"text/template"

	"github.com/guzenok/go-sqltest/sqlmockgen/generator"
	"github.com/guzenok/go-sqltest/sqlmockgen/model"
)

type Descr struct {
	ImportPath      string
	Pkg             *model.Package
	CopyrightHeader string
	DbUrl           string
	OutputPath      string

	SpecTestFuncName string
	GeneratorPath    string
}

func newDescr() *Descr {
	return &Descr{
		GeneratorPath:    generator.ImportPath,
		SpecTestFuncName: "TestXxx",
	}
}

func program(dsc *Descr, f *os.File) (entrypoint string, err error) {
	entrypoint = dsc.SpecTestFuncName
	err = codeTemplate.Execute(f, dsc)
	return
}

var codeTemplate = template.Must(
	template.New("program").Parse(code),
)

// code imports specialized functions and runs generator.
var code = `
package {{.Pkg.Name}}

import (
	"fmt"
	"testing"

	generator {{printf "%q" .GeneratorPath}}
)

func {{.SpecTestFuncName}}(t *testing.T) {
	const copyright = ` + "`{{.CopyrightHeader}}`" + `

	inits := generator.InitDbFunctions{
		{{range $_, $f := .Pkg.Inits}}
			{{printf "%q" $f}}: {{$f}},
		{{end}}
	}
	
	tests := generator.TestDbFunctions{
		{{range $_, $f := .Pkg.Tests}}
			{{printf "%q" $f}}: {{$f}},
		{{end}}
	}

	g := generator.New()
	code, err := g.GenCode(t, {{printf "%q" .DbUrl}}, inits, tests)
	if err != nil {
		t.Fatal(err)
	}

	f, close, err := generator.NewFile({{printf "%q" .OutputPath}})
	if err != nil {
		t.Fatal(err)
	}
	defer close()
	
	fmt.Fprintln(f, "package {{.Pkg.Name}}")
	fmt.Fprintln(f, "// Code generated by SqlMockGen. DO NOT EDIT.")
	fmt.Fprintln(f, "")
	
	if copyright != "" {
		fmt.Fprintln(f, copyright)
		fmt.Fprintln(f, "")
	}
	
	fmt.Fprintln(f, string(code))
}
`
